### ISSUE TITLE
Prod Docker build fails since #3213: frontend code imports e2e/visual/visual-pins.ts, outside the frontend build context

### ISSUE THREAD

**Issue by astrapi69** [astrapi69/adaptive-learner#3239]
## Defect

Since 8864d8296 (#3213, the #3214 random seam) the production frontend image does not build. `frontend/src/lib/random/visual-pin-binding.test.ts` and `frontend/src/test-utils/visual-random-pin.ts` import `../../../(../)e2e/visual/visual-pins`. The frontend image sees only `frontend/`, and `bun run build` runs `tsc -b` over `src` including tests, so it fails with `TS2307: Cannot find module '../../../e2e/visual/visual-pins'`. Locally and in the GitHub Pages build `tsc` sees the whole repository, so nothing else noticed.

Last green docker-build-smoke on develop: 2026-09-23 on ed91df361 (before #3213). Surfaced by PR #3238, whose `bun.lock` change triggered the smoke (run 36001350319).

Impact: the production image cannot be built from develop. That is the desktop launcher and `install.sh` path, and `make docker-build-smoke` is a mandatory release gate. GitHub Pages is not affected.

## Fix

1. Reverse the dependency: the module with `FIXED_NOW_ISO`, `VISUAL_MOUNT_SALT` and `VISUAL_RANDOM_PIN` moves into `frontend/src/test-utils/`; the e2e harness imports it from there (the e2e to frontend direction already exists and is fine).
2. The `ci.yml` frontend-filter line for `e2e/visual/visual-pins.ts` (a505a7062) becomes unnecessary and goes.
3. Guard at the build-context boundary, not at one directory: no import in `frontend/src` may resolve outside the `frontend/` root (any relative path climbing above it, `e2e/` included). The e2e to frontend direction stays allowed. The guard reports how many files it scanned and fails closed on zero.
4. Short term: `frontend/**` triggers docker-build-smoke on PRs, so a frontend change that breaks the image is caught on its own PR.
5. Evidence: `make docker-build-smoke` green; the 13056 binding test unchanged and green.

## Why the gates did not see it

docker-build-smoke decides by path filter whether it runs; #3213 touched no Docker input, so the smoke did not run. A path-filtered gate can only find a break that falls inside its filter: here the break was in a TypeScript file and the effect appeared in the Docker context. Fourth instance of the same class on 2026-09-23/24 (a check that is green without having seen the case): the diff tolerance (#3215), the skipping capture helper (#3224), the spec without a learner (#3236), and this path filter. Which gates decide by path, and which error classes they therefore cannot see, is a separate inventory, not part of this fix.

The #3214 verification did not miss it either: its brief named the production build as the boundary, meaning the Pages build, which sees the whole repository. That a second production build with a narrower context exists was not in the brief. Future verification briefs name the existing build contexts, not only the environment.
